// Sample seed data for Movexa (MVP demo).
// Movie *metadata* is public/factual. Poster & backdrop art is generated on the
// client (brand-consistent SVG) so the demo is fully offline and never shows a
// broken image. `trailer` is a public YouTube id. `videoUrl` points at a
// Creative-Commons demo clip so the streaming player works out of the box.

export const genres = [
  { name: 'Action', description: 'High-octane thrills, fights, and chases.' },
  { name: 'Adventure', description: 'Epic journeys and daring quests.' },
  { name: 'Sci-Fi', description: 'Future worlds, tech, and the unknown.' },
  { name: 'Drama', description: 'Character-driven, emotional stories.' },
  { name: 'Thriller', description: 'Suspense that keeps you on edge.' },
  { name: 'Crime', description: 'Heists, mobsters, and detectives.' },
  { name: 'Fantasy', description: 'Magic, myth, and imagined realms.' },
  { name: 'Animation', description: 'Hand-drawn and computer-animated tales.' },
  { name: 'Comedy', description: 'Laugh-out-loud entertainment.' },
  { name: 'Romance', description: 'Love stories for every mood.' },
  { name: 'Horror', description: 'Scares that linger long after.' },
  { name: 'Mystery', description: 'Puzzles waiting to be solved.' },
];

// Public-domain / Creative-Commons demo streams so playback works out of the box.
const DEMO_VIDEOS = [
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
];

const pickVideo = (i) => DEMO_VIDEOS[i % DEMO_VIDEOS.length];

const raw = [
  {
    title: 'Inception',
    year: 2010,
    runtime: 148,
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    director: 'Christopher Nolan',
    rating: 8.8,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'YoHD9XEInc0',
    description:
      'A skilled thief who steals corporate secrets through dream-sharing technology is given a chance to erase his criminal record — if he can plant an idea into a target’s subconscious.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Dom Cobb' },
      { name: 'Joseph Gordon-Levitt', character: 'Arthur' },
      { name: 'Elliot Page', character: 'Ariadne' },
      { name: 'Tom Hardy', character: 'Eames' },
    ],
    featured: true,
    trending: true,
  },
  {
    title: 'The Dark Knight',
    year: 2008,
    runtime: 152,
    genres: ['Action', 'Crime', 'Drama'],
    director: 'Christopher Nolan',
    rating: 9.0,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'EXeTwQWrcwY',
    description:
      'Batman raises the stakes in his war on crime, but a rising criminal mastermind known as the Joker plunges Gotham into anarchy and forces the Dark Knight to confront his limits.',
    cast: [
      { name: 'Christian Bale', character: 'Bruce Wayne' },
      { name: 'Heath Ledger', character: 'Joker' },
      { name: 'Aaron Eckhart', character: 'Harvey Dent' },
    ],
    featured: true,
    trending: true,
  },
  {
    title: 'Interstellar',
    year: 2014,
    runtime: 169,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    director: 'Christopher Nolan',
    rating: 8.6,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'zSWd7yc1jKg',
    description:
      'With Earth dying, a team of explorers travels through a wormhole near Saturn in a desperate bid to ensure humanity’s survival among the stars.',
    cast: [
      { name: 'Matthew McConaughey', character: 'Cooper' },
      { name: 'Anne Hathaway', character: 'Brand' },
      { name: 'Jessica Chastain', character: 'Murph' },
    ],
    featured: true,
    trending: true,
  },
  {
    title: 'The Matrix',
    year: 1999,
    runtime: 136,
    genres: ['Sci-Fi', 'Action'],
    director: 'The Wachowskis',
    rating: 8.7,
    contentRating: 'R',
    quality: '4K',
    trailer: 'vKQi3bBA1y8',
    description:
      'A hacker learns that his reality is a simulation controlled by machines, and joins a rebellion to free humanity.',
    cast: [
      { name: 'Keanu Reeves', character: 'Neo' },
      { name: 'Laurence Fishburne', character: 'Morpheus' },
      { name: 'Carrie-Anne Moss', character: 'Trinity' },
    ],
    trending: true,
  },
  {
    title: 'Pulp Fiction',
    year: 1994,
    runtime: 154,
    genres: ['Crime', 'Drama'],
    director: 'Quentin Tarantino',
    rating: 8.9,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 's7EdQ4FqbhY',
    description:
      'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    cast: [
      { name: 'John Travolta', character: 'Vincent Vega' },
      { name: 'Samuel L. Jackson', character: 'Jules Winnfield' },
      { name: 'Uma Thurman', character: 'Mia Wallace' },
    ],
    trending: true,
  },
  {
    title: 'Fight Club',
    year: 1999,
    runtime: 139,
    genres: ['Drama', 'Thriller'],
    director: 'David Fincher',
    rating: 8.8,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 'qtRKdVHc-cE',
    description:
      'An insomniac office worker and a soap salesman form an underground fight club that spirals into something far more dangerous.',
    cast: [
      { name: 'Brad Pitt', character: 'Tyler Durden' },
      { name: 'Edward Norton', character: 'The Narrator' },
      { name: 'Helena Bonham Carter', character: 'Marla' },
    ],
  },
  {
    title: 'Forrest Gump',
    year: 1994,
    runtime: 142,
    genres: ['Drama', 'Romance'],
    director: 'Robert Zemeckis',
    rating: 8.8,
    contentRating: 'PG-13',
    quality: 'FHD',
    trailer: 'bLvqoHBptjg',
    description:
      'The extraordinary life of a slow-witted but kind-hearted man from Alabama who unwittingly influences decades of American history.',
    cast: [
      { name: 'Tom Hanks', character: 'Forrest Gump' },
      { name: 'Robin Wright', character: 'Jenny' },
      { name: 'Gary Sinise', character: 'Lieutenant Dan' },
    ],
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    runtime: 142,
    genres: ['Drama', 'Crime'],
    director: 'Frank Darabont',
    rating: 9.3,
    contentRating: 'R',
    quality: 'FHD',
    trailer: '6hB3S9bIaco',
    description:
      'Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.',
    cast: [
      { name: 'Tim Robbins', character: 'Andy Dufresne' },
      { name: 'Morgan Freeman', character: 'Ellis "Red" Redding' },
    ],
    featured: true,
  },
  {
    title: 'Gladiator',
    year: 2000,
    runtime: 155,
    genres: ['Action', 'Adventure', 'Drama'],
    director: 'Ridley Scott',
    rating: 8.5,
    contentRating: 'R',
    quality: '4K',
    trailer: 'owK1qxDselE',
    description:
      'A betrayed Roman general rises from slavery as a gladiator to seek vengeance against the corrupt emperor who murdered his family.',
    cast: [
      { name: 'Russell Crowe', character: 'Maximus' },
      { name: 'Joaquin Phoenix', character: 'Commodus' },
    ],
    trending: true,
  },
  {
    title: 'The Godfather',
    year: 1972,
    runtime: 175,
    genres: ['Crime', 'Drama'],
    director: 'Francis Ford Coppola',
    rating: 9.2,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 'sY1S34973zA',
    description:
      'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.',
    cast: [
      { name: 'Marlon Brando', character: 'Vito Corleone' },
      { name: 'Al Pacino', character: 'Michael Corleone' },
    ],
    featured: true,
  },
  {
    title: 'Avengers: Endgame',
    year: 2019,
    runtime: 181,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'Anthony & Joe Russo',
    rating: 8.4,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'TcMBFSGVi1c',
    description:
      'After the devastating events of Infinity War, the remaining Avengers assemble once more to undo Thanos’s actions and restore balance.',
    cast: [
      { name: 'Robert Downey Jr.', character: 'Tony Stark' },
      { name: 'Chris Evans', character: 'Steve Rogers' },
      { name: 'Scarlett Johansson', character: 'Natasha Romanoff' },
    ],
    trending: true,
  },
  {
    title: 'Avatar',
    year: 2009,
    runtime: 162,
    genres: ['Sci-Fi', 'Adventure', 'Fantasy'],
    director: 'James Cameron',
    rating: 7.9,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: '5PSNL1qE6VY',
    description:
      'A paraplegic marine dispatched to the moon Pandora becomes torn between following orders and protecting the world he feels is his home.',
    cast: [
      { name: 'Sam Worthington', character: 'Jake Sully' },
      { name: 'Zoe Saldana', character: 'Neytiri' },
    ],
  },
  {
    title: 'Joker',
    year: 2019,
    runtime: 122,
    genres: ['Crime', 'Drama', 'Thriller'],
    director: 'Todd Phillips',
    rating: 8.4,
    contentRating: 'R',
    quality: '4K',
    trailer: 'zAGVQLHvwOY',
    description:
      'A failed comedian’s descent into madness ignites a violent revolution in a crumbling Gotham City.',
    cast: [
      { name: 'Joaquin Phoenix', character: 'Arthur Fleck' },
      { name: 'Robert De Niro', character: 'Murray Franklin' },
    ],
    trending: true,
  },
  {
    title: 'Parasite',
    year: 2019,
    runtime: 132,
    genres: ['Drama', 'Thriller', 'Comedy'],
    director: 'Bong Joon-ho',
    rating: 8.5,
    contentRating: 'R',
    quality: '4K',
    trailer: '5xH0HfJHsaY',
    language: 'Korean',
    country: 'South Korea',
    description:
      'A poor family schemes to become employed by a wealthy household, until a shocking twist upends everything.',
    cast: [
      { name: 'Song Kang-ho', character: 'Ki-taek' },
      { name: 'Lee Sun-kyun', character: 'Mr. Park' },
    ],
    featured: true,
    trending: true,
  },
  {
    title: 'Dune',
    year: 2021,
    runtime: 155,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    director: 'Denis Villeneuve',
    rating: 8.0,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'n9xhJrPXop4',
    description:
      'Paul Atreides, a gifted young heir, travels to the deadly desert planet Arrakis to secure the future of his family and people.',
    cast: [
      { name: 'Timothée Chalamet', character: 'Paul Atreides' },
      { name: 'Rebecca Ferguson', character: 'Lady Jessica' },
      { name: 'Zendaya', character: 'Chani' },
    ],
    featured: true,
    trending: true,
  },
  {
    title: 'Django Unchained',
    year: 2012,
    runtime: 165,
    genres: ['Drama', 'Action'],
    director: 'Quentin Tarantino',
    rating: 8.4,
    contentRating: 'R',
    quality: 'FHD',
    trailer: '0fUCuvNlOCg',
    description:
      'A freed slave sets out with a German bounty hunter to rescue his wife from a brutal Mississippi plantation owner.',
    cast: [
      { name: 'Jamie Foxx', character: 'Django' },
      { name: 'Christoph Waltz', character: 'Dr. King Schultz' },
      { name: 'Leonardo DiCaprio', character: 'Calvin Candie' },
    ],
  },
  {
    title: 'The Wolf of Wall Street',
    year: 2013,
    runtime: 180,
    genres: ['Crime', 'Drama', 'Comedy'],
    director: 'Martin Scorsese',
    rating: 8.2,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 'iszwuX1AK6A',
    description:
      'The true story of a stockbroker’s rise to a wealthy high-life and his fall involving fraud and corruption.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Jordan Belfort' },
      { name: 'Jonah Hill', character: 'Donnie Azoff' },
    ],
  },
  {
    title: 'Titanic',
    year: 1997,
    runtime: 194,
    genres: ['Drama', 'Romance'],
    director: 'James Cameron',
    rating: 7.9,
    contentRating: 'PG-13',
    quality: 'FHD',
    trailer: 'kVrqfYjkTdQ',
    description:
      'A young aristocrat and a poor artist fall in love aboard the ill-fated R.M.S. Titanic.',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Jack Dawson' },
      { name: 'Kate Winslet', character: 'Rose DeWitt Bukater' },
    ],
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    runtime: 178,
    genres: ['Fantasy', 'Adventure', 'Drama'],
    director: 'Peter Jackson',
    rating: 8.9,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'V75dMMIW2B4',
    description:
      'A hobbit inherits a ring of terrible power and sets out with a fellowship to destroy it before it can fall into the wrong hands.',
    cast: [
      { name: 'Elijah Wood', character: 'Frodo Baggins' },
      { name: 'Ian McKellen', character: 'Gandalf' },
      { name: 'Viggo Mortensen', character: 'Aragorn' },
    ],
    featured: true,
  },
  {
    title: 'Spirited Away',
    year: 2001,
    runtime: 125,
    genres: ['Animation', 'Fantasy', 'Adventure'],
    director: 'Hayao Miyazaki',
    rating: 8.6,
    contentRating: 'PG',
    quality: 'FHD',
    trailer: 'ByXuk9QqQkk',
    language: 'Japanese',
    country: 'Japan',
    description:
      'A young girl wanders into a world of spirits and must work to free her parents and find her way home.',
    cast: [{ name: 'Rumi Hiiragi', character: 'Chihiro (voice)' }],
    trending: true,
  },
  {
    title: 'Whiplash',
    year: 2014,
    runtime: 106,
    genres: ['Drama'],
    director: 'Damien Chazelle',
    rating: 8.5,
    contentRating: 'R',
    quality: 'FHD',
    trailer: '7d_jQycdQGo',
    description:
      'A promising young drummer enrolls at a cut-throat music conservatory where his dreams collide with a ruthless instructor.',
    cast: [
      { name: 'Miles Teller', character: 'Andrew Neiman' },
      { name: 'J.K. Simmons', character: 'Terence Fletcher' },
    ],
  },
  {
    title: 'The Social Network',
    year: 2010,
    runtime: 120,
    genres: ['Drama'],
    director: 'David Fincher',
    rating: 7.8,
    contentRating: 'PG-13',
    quality: 'FHD',
    trailer: 'lB95KLmpLR4',
    description:
      'The story of how a Harvard student created a social network that would change the world — and cost him his friendships.',
    cast: [
      { name: 'Jesse Eisenberg', character: 'Mark Zuckerberg' },
      { name: 'Andrew Garfield', character: 'Eduardo Saverin' },
    ],
  },
  {
    title: 'Mad Max: Fury Road',
    year: 2015,
    runtime: 120,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'George Miller',
    rating: 8.1,
    contentRating: 'R',
    quality: '4K',
    trailer: 'hEJnMQG9ev8',
    description:
      'In a post-apocalyptic wasteland, a drifter and a rebellious warrior flee a tyrant across the desert in a relentless chase.',
    cast: [
      { name: 'Tom Hardy', character: 'Max Rockatansky' },
      { name: 'Charlize Theron', character: 'Furiosa' },
    ],
    trending: true,
  },
  {
    title: 'Blade Runner 2049',
    year: 2017,
    runtime: 164,
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    director: 'Denis Villeneuve',
    rating: 8.0,
    contentRating: 'R',
    quality: '4K',
    trailer: 'gCcx85zbxz4',
    description:
      'A young blade runner uncovers a long-buried secret that could plunge what’s left of society into chaos.',
    cast: [
      { name: 'Ryan Gosling', character: 'K' },
      { name: 'Harrison Ford', character: 'Rick Deckard' },
    ],
  },
  {
    title: 'Deadpool',
    year: 2016,
    runtime: 108,
    genres: ['Action', 'Comedy'],
    director: 'Tim Miller',
    rating: 8.0,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 'ONHBaC-pfsk',
    description:
      'A wisecracking mercenary gains accelerated healing powers and adopts the alter ego Deadpool to hunt the man who nearly destroyed his life.',
    cast: [{ name: 'Ryan Reynolds', character: 'Wade Wilson / Deadpool' }],
  },
  {
    title: 'Guardians of the Galaxy',
    year: 2014,
    runtime: 121,
    genres: ['Action', 'Adventure', 'Comedy'],
    director: 'James Gunn',
    rating: 8.0,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'd96cjJhvlMA',
    description:
      'A band of intergalactic misfits must pull together to stop a fanatical warrior from destroying the galaxy.',
    cast: [
      { name: 'Chris Pratt', character: 'Peter Quill / Star-Lord' },
      { name: 'Zoe Saldana', character: 'Gamora' },
    ],
  },
  {
    title: 'Tenet',
    year: 2020,
    runtime: 150,
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    director: 'Christopher Nolan',
    rating: 7.3,
    contentRating: 'PG-13',
    quality: '4K',
    trailer: 'L3pk_TBkihU',
    description:
      'Armed with only the word “Tenet,” a secret agent journeys through a twilight world of international espionage and inverted time.',
    cast: [
      { name: 'John David Washington', character: 'The Protagonist' },
      { name: 'Robert Pattinson', character: 'Neil' },
    ],
  },
  {
    title: '1917',
    year: 2019,
    runtime: 119,
    genres: ['Drama', 'Thriller', 'Action'],
    director: 'Sam Mendes',
    rating: 8.2,
    contentRating: 'R',
    quality: '4K',
    trailer: 'gZjQROMAh_s',
    description:
      'Two young British soldiers are given a near-impossible mission to deliver a message that could save 1,600 men.',
    cast: [
      { name: 'George MacKay', character: 'Lance Corporal Schofield' },
      { name: 'Dean-Charles Chapman', character: 'Lance Corporal Blake' },
    ],
  },
  {
    title: 'John Wick',
    year: 2014,
    runtime: 101,
    genres: ['Action', 'Thriller', 'Crime'],
    director: 'Chad Stahelski',
    rating: 7.4,
    contentRating: 'R',
    quality: 'FHD',
    trailer: 'C0BMx-qxsP4',
    description:
      'A retired hitman is forced back into the underworld to hunt down the men who took everything from him.',
    cast: [{ name: 'Keanu Reeves', character: 'John Wick' }],
    trending: true,
  },
  {
    title: 'Coco',
    year: 2017,
    runtime: 105,
    genres: ['Animation', 'Adventure', 'Fantasy'],
    director: 'Lee Unkrich',
    rating: 8.4,
    contentRating: 'PG',
    quality: '4K',
    trailer: 'Rvr68u6k5sI',
    description:
      'A music-loving boy is transported to the colorful Land of the Dead, where he seeks the truth about his family’s history.',
    cast: [{ name: 'Anthony Gonzalez', character: 'Miguel (voice)' }],
  },
];

// Attach demo defaults + a demo stream URL.
export const movies = raw.map((m, i) => ({
  language: 'English',
  country: 'USA',
  type: 'movie',
  streamingStatus: 'available',
  published: true,
  releaseDate: new Date(`${m.year}-06-15`),
  popularity: Math.round((m.rating * 10 + (raw.length - i)) * 10) / 10,
  views: Math.floor(Math.random() * 40000) + 2000,
  videoUrl: pickVideo(i),
  ...m,
}));

export const demoUsers = [
  {
    name: 'Movexa Admin',
    email: 'admin@movexa.test',
    password: 'admin123',
    role: 'super_admin',
  },
  {
    name: 'Demo User',
    email: 'user@movexa.test',
    password: 'user123',
    role: 'user',
  },
];
